default: true

# Spaces for indent
MD007:
  indent: 4

# Line length
MD013: false

# Multiple headings with the same content
MD024:
  siblings_only: true

# Inline HTML
MD033: false

# Images should have alternate text (alt text)
MD045: false
